feat: add fios-sequenciados module
dojo-coders/keep-talking-defuser-helper pull request #26
Opened 2021-01-10 14:33 UTC by lvolcov

#8

2021-01-11 03:24 UTC, jampow requested changes

2021-01-11 03:24 UTC, jampow commented on src/622/modules/fios-sequenciados/index.js
> +   * @param {Object} lastStep - Objeto que traz a informação das interações anteriores
Quais são as chaves desse objeto? Vc pode especificar melhor com linhas adicionais

```* @param {string} lastStep.chave - descrição daquela chave de dentro do objeto```

2021-01-11 03:24 UTC, jampow commented on src/622/modules/fios-sequenciados/index.js
> +   * @returns {string[]} Array com o objeto newLastStep na posição 0, que é o resultado do merge to lastStep com o current Step e três strings podendo ser true, false e null
Essa descrição está muito técnica, não precisa colocar o nome das variáveis envolvidas. Pode ser algo explicando o retorno mesmo, como "Array contendo os números dos fios a serem cortados no passo atual", por exemplo

2021-01-11 03:24 UTC, jampow commented on src/622/modules/fios-sequenciados/index.js
> +    const newLastStep = {...lastStep, ...currentStep}
Não tem nenhuma validação para caso o currentstep não seja enviado ou não seja um objeto como o esperado. Se for uma string, bill ou undefined ja vai quebrar, melhor configurar um default na assinatura da função e validar se é um objeto antes de usar o spread operator

2021-01-11 03:24 UTC, jampow commented on src/622/modules/fios-sequenciados/index.test.js
> +    }
Se as variáveis são usadas apenas em um teste, é melhor que fiquem dentro do escopo do `it`. Colocamos assim fora só quando elas são usadas em mais de um teste.

2021-01-11 03:24 UTC, jampow commented on src/622/modules/fios-sequenciados/index.test.js
> +    it('Deve retornar true e true', () => {
Sem descrições técnicas, o teste já vai falar o q é esperado. Pode passar uma descrição como "Deve mandar cortar todos os fios quando tiver um preto conectado em C e um vermelho em C."

2021-01-11 03:24 UTC, jampow commented on src/622/modules/fios-sequenciados/index.test.js
> +        "1" : ["blue", "A", null],
Eu não entendi esse terceiro parâmetro que é sempre null. Pra que serve?

2021-01-11 10:50 UTC, lvolcov commented on src/622/modules/fios-sequenciados/index.test.js
> +        "1" : ["blue", "A", null],
O terceiro parâmetro é onde fica guardada a resposta de cada step. True corta, false nao corta e null é porque ainda não foi carimbado.

2021-01-13 01:30 UTC, jampow commented on src/622/modules/fios-sequenciados/index.test.js
> +        "1" : ["blue", "A", null],
faz uns testes com este terceiro parâmetro, ou tira ele e deixa para a interface cuidar do histórico. nos seus testes vc está mostrando que não precisaríamos do terceiro parâmetro, já que ele é sempre null

2021-01-24 14:48 UTC, lvolcov commented
Meu próximo commit deve resolver todos os comentários acima.

2021-01-25 02:22 UTC, jampow approved these changes

2021-01-28 20:38 UTC, gledsoncr approved these changes

2021-01-28 22:47 UTC, merged